name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      max-parallel: 2
      matrix:
        node-version: [16, 18, 20]
        os: [ubuntu-latest, windows-latest, macos-latest]
        # test only nodejs v18 on win and mac
        exclude:
          - os: macos-latest
            node-version: 16
          - os: macos-latest
            node-version: 20
          - os: windows-latest
            node-version: 16
          - os: windows-latest
            node-version: 20

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Dependencies
        run: npm ci

      - name: Build Packages
        run: npm run build

      - name: Run Tests
        run: npm test

      - name: Run Prettier
        if: matrix.os == 'ubuntu-latest'
        run: npm run format

      - name: Run ESLint
        if: matrix.os == 'ubuntu-latest'
        run: npm run lint

      - name: Upload coverage to Codecov
        if: matrix.os == 'ubuntu-latest'
        uses: codecov/codecov-action@v2
